name: 080-resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: HoussemDellai/github-actions-course/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: Houssem
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-B:
    uses: HoussemDellai/github-actions-course/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: Dellai
    secrets:
      token: ${{ secrets.TOKEN }}